// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | FooterSlice
  | ConsultationSlice
  | PriceSectionSlice
  | QuestionSectionSlice
  | WhatYouNeedSlice
  | ExampleSlice
  | ResultsSlice
  | SectionImageSlice
  | HeaderSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *SubgroupItem → SubgroupList*
 */
export interface SubgroupitemDocumentDataSubgrouplistItem {
  /**
   * SubgroupItem field in *SubgroupItem → SubgroupList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subgroupitem.subgrouplist[].subgroupitem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subgroupitem: prismic.RichTextField;
}

/**
 * Content for SubgroupItem documents
 */
interface SubgroupitemDocumentData {
  /**
   * SubgroupTitle field in *SubgroupItem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subgroupitem.subgrouptitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subgrouptitle: prismic.RichTextField;

  /**
   * SubgroupList field in *SubgroupItem*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: subgroupitem.subgrouplist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  subgrouplist: prismic.GroupField<
    Simplify<SubgroupitemDocumentDataSubgrouplistItem>
  >;
}

/**
 * SubgroupItem document from Prismic
 *
 * - **API ID**: `subgroupitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubgroupitemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubgroupitemDocumentData>,
    "subgroupitem",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SubgroupitemDocument;

/**
 * Item in *Consultation → Consultation → Primary → List*
 */
export interface ConsultationSliceDefaultPrimaryListItem {
  /**
   * Price field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;

  /**
   * TitleInclud field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].titleinclud
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleinclud: prismic.RichTextField;

  /**
   * Description1 field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].description1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].description2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * Description3 field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].description3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description3: prismic.RichTextField;

  /**
   * Description4 field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].description4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description4: prismic.RichTextField;

  /**
   * Description5 field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].description5
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description5: prismic.RichTextField;

  /**
   * LinkToSection field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[].linktosection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linktosection: prismic.LinkField;

  /**
   * TitleLink field in *Consultation → Consultation → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book consultation
   * - **API ID Path**: consultation.default.primary.list[].titlelink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titlelink: prismic.KeyTextField;
}

/**
 * Primary content in *Consultation → Consultation → Primary*
 */
export interface ConsultationSliceDefaultPrimary {
  /**
   * Title field in *Consultation → Consultation → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * List field in *Consultation → Consultation → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<ConsultationSliceDefaultPrimaryListItem>>;
}

/**
 * Consultation variation for Consultation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConsultationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConsultationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Consultation*
 */
type ConsultationSliceVariation = ConsultationSliceDefault;

/**
 * Consultation Shared Slice
 *
 * - **API ID**: `consultation`
 * - **Description**: Consultation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConsultationSlice = prismic.SharedSlice<
  "consultation",
  ConsultationSliceVariation
>;

/**
 * Item in *Example → Default → Primary → ExamplesList*
 */
export interface ExampleSliceDefaultPrimaryExampleslistItem {
  /**
   * IconExample field in *Example → Default → Primary → ExamplesList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.exampleslist[].iconexample
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconexample: prismic.ImageField<never>;

  /**
   * TitleExample field in *Example → Default → Primary → ExamplesList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.exampleslist[].titleexample
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleexample: prismic.RichTextField;

  /**
   * DescriptionExample field in *Example → Default → Primary → ExamplesList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.exampleslist[].descriptionexample
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionexample: prismic.RichTextField;
}

/**
 * Primary content in *Example → Default → Primary*
 */
export interface ExampleSliceDefaultPrimary {
  /**
   * ExamplesTitle field in *Example → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.examplestitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  examplestitle: prismic.RichTextField;

  /**
   * ExamplesList field in *Example → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.exampleslist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  exampleslist: prismic.GroupField<
    Simplify<ExampleSliceDefaultPrimaryExampleslistItem>
  >;
}

/**
 * Default variation for Example Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExampleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Example*
 */
type ExampleSliceVariation = ExampleSliceDefault;

/**
 * Example Shared Slice
 *
 * - **API ID**: `example`
 * - **Description**: Example
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSlice = prismic.SharedSlice<
  "example",
  ExampleSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * ImageHero field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.imagehero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagehero: prismic.ImageField<never>;

  /**
   * ContactWithMe field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contactwithme
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactwithme: prismic.RichTextField;

  /**
   * Name field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Hobby field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.hobby
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hobby: prismic.RichTextField;

  /**
   * LinkWhatsApp field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: WhatsApp
   * - **API ID Path**: footer.default.primary.linkwhatsapp
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkwhatsapp: prismic.LinkField;

  /**
   * TextLinkWhatsApp field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.textlinkwhatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkwhatsapp: prismic.KeyTextField;

  /**
   * LinkTelegram field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Telegram
   * - **API ID Path**: footer.default.primary.linktelegram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linktelegram: prismic.LinkField;

  /**
   * TextLinkTelegram field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.textlinktelegram
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinktelegram: prismic.KeyTextField;

  /**
   * BackgroundImage field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Header → Default → Primary → Languages*
 */
export interface HeaderSliceDefaultPrimaryLanguagesItem {
  /**
   * Ukraine field in *Header → Default → Primary → Languages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[].ukraine
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ukraine: prismic.KeyTextField;

  /**
   * English field in *Header → Default → Primary → Languages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[].english
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  english: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * LinkMetods field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkmetods
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkmetods: prismic.LinkField;

  /**
   * TextLinkMetod field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkmetod
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkmetod: prismic.KeyTextField;

  /**
   * LinkPrice field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkprice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkprice: prismic.LinkField;

  /**
   * TextLinkPrice field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkprice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkprice: prismic.KeyTextField;

  /**
   * LinkAdvice field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkadvice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkadvice: prismic.LinkField;

  /**
   * TextLinkAdvice field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkadvice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkadvice: prismic.KeyTextField;

  /**
   * LinkSession field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linksession
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linksession: prismic.LinkField;

  /**
   * TextLinkSession field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinksession
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinksession: prismic.KeyTextField;

  /**
   * Language field in *Header → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: UA
   * - **API ID Path**: header.default.primary.language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<"UA" | "EN", "filled">;

  /**
   * Languages field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  languages: prismic.GroupField<
    Simplify<HeaderSliceDefaultPrimaryLanguagesItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * HeroName field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heroname: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * TelNumber field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.telnumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telnumber: prismic.KeyTextField;

  /**
   * HeroImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *PriceSection → Default → Primary → PriceList*
 */
export interface PriceSectionSliceDefaultPrimaryPricelistItem {
  /**
   * IconPlan field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].iconplan
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconplan: prismic.ImageField<never>;

  /**
   * TitlePlan field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].titleplan
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleplan: prismic.RichTextField;

  /**
   * IncludeTitle field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].includetitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  includetitle: prismic.RichTextField;

  /**
   * Description1 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * Description3 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description3: prismic.RichTextField;

  /**
   * Description4 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description4: prismic.RichTextField;

  /**
   * Description5 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description5
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description5: prismic.RichTextField;

  /**
   * Description6 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description6
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description6: prismic.RichTextField;

  /**
   * Description7 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description7
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description7: prismic.RichTextField;

  /**
   * Description8 field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].description8
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description8: prismic.RichTextField;

  /**
   * Language field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].language
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  language: prismic.RichTextField;

  /**
   * Price field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;

  /**
   * LinkToSectionPayment field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].linktosectionpayment
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linktosectionpayment: prismic.LinkField;

  /**
   * TextLinkPaymant field in *PriceSection → Default → Primary → PriceList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[].textlinkpaymant
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkpaymant: prismic.KeyTextField;
}

/**
 * Primary content in *PriceSection → Default → Primary*
 */
export interface PriceSectionSliceDefaultPrimary {
  /**
   * Title field in *PriceSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * PriceList field in *PriceSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: price_section.default.primary.pricelist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pricelist: prismic.GroupField<
    Simplify<PriceSectionSliceDefaultPrimaryPricelistItem>
  >;
}

/**
 * Default variation for PriceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PriceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PriceSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PriceSection*
 */
type PriceSectionSliceVariation = PriceSectionSliceDefault;

/**
 * PriceSection Shared Slice
 *
 * - **API ID**: `price_section`
 * - **Description**: PriceSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PriceSectionSlice = prismic.SharedSlice<
  "price_section",
  PriceSectionSliceVariation
>;

/**
 * Item in *QuestionSection → Default → Primary → ListQuestion*
 */
export interface QuestionSectionSliceDefaultPrimaryListquestionItem {
  /**
   * Question field in *QuestionSection → Default → Primary → ListQuestion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.listquestion[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * answer field in *QuestionSection → Default → Primary → ListQuestion*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.listquestion[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *QuestionSection → Default → Primary*
 */
export interface QuestionSectionSliceDefaultPrimary {
  /**
   * TitleSection field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.titlesection
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlesection: prismic.RichTextField;

  /**
   * ListQuestion field in *QuestionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: question_section.default.primary.listquestion[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  listquestion: prismic.GroupField<
    Simplify<QuestionSectionSliceDefaultPrimaryListquestionItem>
  >;
}

/**
 * Default variation for QuestionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuestionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuestionSection*
 */
type QuestionSectionSliceVariation = QuestionSectionSliceDefault;

/**
 * QuestionSection Shared Slice
 *
 * - **API ID**: `question_section`
 * - **Description**: QuestionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSectionSlice = prismic.SharedSlice<
  "question_section",
  QuestionSectionSliceVariation
>;

/**
 * Item in *Results → Default → Primary → ResultsList*
 */
export interface ResultsSliceDefaultPrimaryResultslistItem {
  /**
   * Icon field in *Results → Default → Primary → ResultsList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.resultslist[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * TitleList field in *Results → Default → Primary → ResultsList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.resultslist[].titlelist
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlelist: prismic.RichTextField;

  /**
   * ItemDescription field in *Results → Default → Primary → ResultsList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.resultslist[].itemdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itemdescription: prismic.RichTextField;
}

/**
 * Primary content in *Results → Default → Primary*
 */
export interface ResultsSliceDefaultPrimary {
  /**
   * TitleResultSection field in *Results → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.titleresultsection
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleresultsection: prismic.RichTextField;

  /**
   * ResultSectionImage field in *Results → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.resultsectionimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  resultsectionimage: prismic.ImageField<never>;

  /**
   * ResultsList field in *Results → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.resultslist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  resultslist: prismic.GroupField<
    Simplify<ResultsSliceDefaultPrimaryResultslistItem>
  >;
}

/**
 * Default variation for Results Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResultsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Results*
 */
type ResultsSliceVariation = ResultsSliceDefault;

/**
 * Results Shared Slice
 *
 * - **API ID**: `results`
 * - **Description**: Results
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSlice = prismic.SharedSlice<
  "results",
  ResultsSliceVariation
>;

/**
 * Item in *MetodAndImages → Default → Primary → Images*
 */
export interface SectionImageSliceDefaultPrimaryImagseItem {
  /**
   * Image field in *MetodAndImages → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagse[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *MetodAndImages → Default → Primary → DescriptionMetodList*
 */
export interface SectionImageSliceDefaultPrimaryDescriptionmetodlistItem {
  /**
   * ItemList field in *MetodAndImages → Default → Primary → DescriptionMetodList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetodlist[].itemlist
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itemlist: prismic.RichTextField;
}

/**
 * Item in *MetodAndImages → Default → Primary → ImagesBotttom*
 */
export interface SectionImageSliceDefaultPrimaryImagesbotttomItem {
  /**
   * image field in *MetodAndImages → Default → Primary → ImagesBotttom*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagesbotttom[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *MetodAndImages → Default → Primary*
 */
export interface SectionImageSliceDefaultPrimary {
  /**
   * Images field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagse[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagse: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryImagseItem>
  >;

  /**
   * Title field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * DescriptionMetod field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetod
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionmetod: prismic.RichTextField;

  /**
   * DescriptionMetodList field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetodlist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  descriptionmetodlist: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryDescriptionmetodlistItem>
  >;

  /**
   * GolOfRegress field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.golofregress
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  golofregress: prismic.RichTextField;

  /**
   * UsefulDescription field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.usefuldescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  usefuldescription: prismic.RichTextField;

  /**
   * ImagesBotttom field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagesbotttom[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagesbotttom: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryImagesbotttomItem>
  >;
}

/**
 * Default variation for MetodAndImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MetodAndImages*
 */
type SectionImageSliceVariation = SectionImageSliceDefault;

/**
 * MetodAndImages Shared Slice
 *
 * - **API ID**: `section_image`
 * - **Description**: SectionImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionImageSlice = prismic.SharedSlice<
  "section_image",
  SectionImageSliceVariation
>;

/**
 * Item in *WhatYouNeed → Default → Primary → List*
 */
export interface WhatYouNeedSliceDefaultPrimaryListItem {
  /**
   * Icon field in *WhatYouNeed → Default → Primary → List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_need.default.primary.list[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * TitleItem field in *WhatYouNeed → Default → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_need.default.primary.list[].titleitem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titleitem: prismic.RichTextField;

  /**
   * ItemDescription field in *WhatYouNeed → Default → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_need.default.primary.list[].itemdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itemdescription: prismic.RichTextField;
}

/**
 * Primary content in *WhatYouNeed → Default → Primary*
 */
export interface WhatYouNeedSliceDefaultPrimary {
  /**
   * Title field in *WhatYouNeed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_need.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * List field in *WhatYouNeed → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_need.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<WhatYouNeedSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for WhatYouNeed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatYouNeedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatYouNeedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatYouNeed*
 */
type WhatYouNeedSliceVariation = WhatYouNeedSliceDefault;

/**
 * WhatYouNeed Shared Slice
 *
 * - **API ID**: `what_you_need`
 * - **Description**: WhatYouNeed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatYouNeedSlice = prismic.SharedSlice<
  "what_you_need",
  WhatYouNeedSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SubgroupitemDocument,
      SubgroupitemDocumentData,
      SubgroupitemDocumentDataSubgrouplistItem,
      AllDocumentTypes,
      ConsultationSlice,
      ConsultationSliceDefaultPrimaryListItem,
      ConsultationSliceDefaultPrimary,
      ConsultationSliceVariation,
      ConsultationSliceDefault,
      ExampleSlice,
      ExampleSliceDefaultPrimaryExampleslistItem,
      ExampleSliceDefaultPrimary,
      ExampleSliceVariation,
      ExampleSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimaryLanguagesItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PriceSectionSlice,
      PriceSectionSliceDefaultPrimaryPricelistItem,
      PriceSectionSliceDefaultPrimary,
      PriceSectionSliceVariation,
      PriceSectionSliceDefault,
      QuestionSectionSlice,
      QuestionSectionSliceDefaultPrimaryListquestionItem,
      QuestionSectionSliceDefaultPrimary,
      QuestionSectionSliceVariation,
      QuestionSectionSliceDefault,
      ResultsSlice,
      ResultsSliceDefaultPrimaryResultslistItem,
      ResultsSliceDefaultPrimary,
      ResultsSliceVariation,
      ResultsSliceDefault,
      SectionImageSlice,
      SectionImageSliceDefaultPrimaryImagseItem,
      SectionImageSliceDefaultPrimaryDescriptionmetodlistItem,
      SectionImageSliceDefaultPrimaryImagesbotttomItem,
      SectionImageSliceDefaultPrimary,
      SectionImageSliceVariation,
      SectionImageSliceDefault,
      WhatYouNeedSlice,
      WhatYouNeedSliceDefaultPrimaryListItem,
      WhatYouNeedSliceDefaultPrimary,
      WhatYouNeedSliceVariation,
      WhatYouNeedSliceDefault,
    };
  }
}
