// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = SectionImageSlice | HeaderSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Header → Default → Primary → Languages*
 */
export interface HeaderSliceDefaultPrimaryLanguagesItem {
  /**
   * Ukraine field in *Header → Default → Primary → Languages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[].ukraine
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ukraine: prismic.KeyTextField;

  /**
   * English field in *Header → Default → Primary → Languages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[].english
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  english: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * LinkMetods field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkmetods
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkmetods: prismic.LinkField;

  /**
   * TextLinkMetod field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkmetod
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkmetod: prismic.KeyTextField;

  /**
   * LinkPrice field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkprice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkprice: prismic.LinkField;

  /**
   * TextLinkPrice field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkprice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkprice: prismic.KeyTextField;

  /**
   * LinkAdvice field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linkadvice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkadvice: prismic.LinkField;

  /**
   * TextLinkAdvice field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinkadvice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinkadvice: prismic.KeyTextField;

  /**
   * LinkSession field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.linksession
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linksession: prismic.LinkField;

  /**
   * TextLinkSession field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.textlinksession
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textlinksession: prismic.KeyTextField;

  /**
   * Language field in *Header → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: UA
   * - **API ID Path**: header.default.primary.language
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  language: prismic.SelectField<"UA" | "EN", "filled">;

  /**
   * Languages field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.languages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  languages: prismic.GroupField<
    Simplify<HeaderSliceDefaultPrimaryLanguagesItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * HeroName field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heroname: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * TelNumber field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.telnumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telnumber: prismic.KeyTextField;

  /**
   * HeroImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *MetodAndImages → Default → Primary → Images*
 */
export interface SectionImageSliceDefaultPrimaryImagseItem {
  /**
   * Image field in *MetodAndImages → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagse[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *MetodAndImages → Default → Primary → DescriptionMetodList*
 */
export interface SectionImageSliceDefaultPrimaryDescriptionmetodlistItem {
  /**
   * ItemList field in *MetodAndImages → Default → Primary → DescriptionMetodList*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetodlist[].itemlist
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itemlist: prismic.RichTextField;
}

/**
 * Item in *MetodAndImages → Default → Primary → ImagesBotttom*
 */
export interface SectionImageSliceDefaultPrimaryImagesbotttomItem {
  /**
   * image field in *MetodAndImages → Default → Primary → ImagesBotttom*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagesbotttom[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *MetodAndImages → Default → Primary*
 */
export interface SectionImageSliceDefaultPrimary {
  /**
   * Images field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagse[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagse: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryImagseItem>
  >;

  /**
   * Title field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * DescriptionMetod field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetod
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionmetod: prismic.RichTextField;

  /**
   * DescriptionMetodList field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.descriptionmetodlist[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  descriptionmetodlist: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryDescriptionmetodlistItem>
  >;

  /**
   * GolOfRegress field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.golofregress
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  golofregress: prismic.RichTextField;

  /**
   * UsefulDescription field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.usefuldescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  usefuldescription: prismic.RichTextField;

  /**
   * ImagesBotttom field in *MetodAndImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: section_image.default.primary.imagesbotttom[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  imagesbotttom: prismic.GroupField<
    Simplify<SectionImageSliceDefaultPrimaryImagesbotttomItem>
  >;
}

/**
 * Default variation for MetodAndImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MetodAndImages*
 */
type SectionImageSliceVariation = SectionImageSliceDefault;

/**
 * MetodAndImages Shared Slice
 *
 * - **API ID**: `section_image`
 * - **Description**: SectionImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionImageSlice = prismic.SharedSlice<
  "section_image",
  SectionImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeaderSlice,
      HeaderSliceDefaultPrimaryLanguagesItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SectionImageSlice,
      SectionImageSliceDefaultPrimaryImagseItem,
      SectionImageSliceDefaultPrimaryDescriptionmetodlistItem,
      SectionImageSliceDefaultPrimaryImagesbotttomItem,
      SectionImageSliceDefaultPrimary,
      SectionImageSliceVariation,
      SectionImageSliceDefault,
    };
  }
}
