// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  consultation: dynamic(() => import("./Consultation")),
  example: dynamic(() => import("./Example")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  price_section: dynamic(() => import("./PriceSection")),
  question_section: dynamic(() => import("./QuestionSection")),
  results: dynamic(() => import("./Results")),
  section_image: dynamic(() => import("./MetodAndImages")),
  what_you_need: dynamic(() => import("./WhatYouNeed")),
};
