// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  section_image: dynamic(() => import("./MetodAndImages")),
};
